### ISSUE TITLE
**Feature: python 슈퍼유저 생성 시 오류**

### ISSUE THREAD

**Issue by jeihomme** [pyeon-air/pyeon_air#28]
## 1. 기능 선정
- DB접근을 하기 위한 파이썬의 슈퍼유저 생성 중 오류

## 2. 세부 내용
- 메인페이지 -> 로그인페이지 -> 로그인 시도 -> 오류 인 상황
- 1. 현 PC의 DB에서 전달받은 pyeonair의 계정 데이터로 시도했으나 실패
- 2. 슈퍼유저 생성을 위해 python manage.py createsuperuser 입력
- 3. 추가내용과 같은 오류 발생하여, 추가설정이 필요한건지 확인요청
-

## 3. 추가 내용( 오류 로그 )
- $ python manage.py createsuperuser
Traceback (most recent call last):
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\module_loading.py", line 30, in import_string 
    return cached_import(module_path, class_name)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import 
    import_module(module_path)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework_jwt\authentication.py", line 4, in <module> 
    from django.utils.encoding import smart_text
ImportError: cannot import name 'smart_text' from 'django.utils.encoding' (C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\encoding.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyeon_air\manage.py", line 22, in <module>
    main()
  File "D:\pyeon_air\manage.py", line 18, in main
    execute_from_command_line(sys.argv)        
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 419, in execute  
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)   
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 412, in execute      
    self.check()
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 438, in check        
    all_issues = checks.run_checks(
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\registry.py", line 77, in run_checks    
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config  
    return check_resolver(resolver)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver    
    return check_method()
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 448, in check
    for pattern in self.url_patterns:
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 634, in url_patterns       
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\urls\resolvers.py", line 627, in urlconf_module     
    return import_module(self.urlconf_name)    
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\pyeon_air\pyeonAir\urls.py", line 19, in <module>
    from drf_yasg.views import get_schema_view 
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\drf_yasg\views.py", line 10, in <module>
    from rest_framework.views import APIView   
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\schemas\__init__.py", line 33, in <module>  
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__      
    val = perform_import(val, attr)
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\settings.py", line 168, in perform_import   
    return [import_from_string(item, setting_name) for item in val]
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\settings.py", line 168, in <listcomp>       
    return [import_from_string(item, setting_name) for item in val]
  File "C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_jwt.authentication.JSONWebTokenAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name 'smart_text' 
from 'django.utils.encoding' (C:\Users\BIZMINE\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\encoding.py).

**Comment by jeihomme** [comment]
슈퍼유저 생성방법
1. docker desktop 프로그램 열기
2. 컨테이너 열기
3. pyeon_air 컨테이너의 하위 컨테이너 django CLI 버튼 클릭
4. [ python manage.py createsuperuser ] 명령어 입력

해당 방법으로 슈퍼유저 우선 생성하여 :8000/admin으로 접속 확인했습니다
